Repository gchq/Gaffer, pull requests merged in 2024-08, with the labels that each got.

#3260 Gh-3259: Improve release process
  .github/release-notes.yml
  .github/release.yml
  .github/workflows/create-release-branch.yaml
  .github/workflows/release.yaml
Labels: automation

#3261 Gh-3258: Sonarcloud Issues
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/ByteBufferUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/CloseableUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/CollectionUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/FieldUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/GroupUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/JsonAssert.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/JsonUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/LongUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/PropertiesUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/StreamUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/StringUtilTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/ToStringBuilderTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/elementvisibilityutil/ArrayByteSequenceTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/elementvisibilityutil/AuthorisationsTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/elementvisibilityutil/ElementVisibilityTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/elementvisibilityutil/VisibilityEvaluatorTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/AlwaysValidTrueTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/CachingIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/ConsumableBlockingQueueTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/EmptyIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/LimitedInMemorySortedIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/RepeatItemIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/StreamIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/StreamIteratorTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/SuppliedIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/TransformIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/iterable/TransformOneToManyIterableTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/pair/PairTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/stream/GafferCollectorTest.java
  core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/stream/StreamsTest.java
  core/graph/src/test/java/uk/gov/gchq/gaffer/graph/hook/NamedOperationResolverTest.java
  core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/DeleteAllDataTest.java
  core/type/src/test/java/uk/gov/gchq/gaffer/serialisation/CustomMapSerialiserTest.java
  library/cache-library/jcs-cache-service/src/test/java/uk/gov/gchq/gaffer/cache/impl/JcsCacheTest.java
  library/hdfs-library/src/test/java/uk/gov/gchq/gaffer/hdfs/integration/loader/AddElementsFromHdfsLoaderIT.java
  library/time-library/src/test/java/uk/gov/gchq/gaffer/time/serialisation/RBMBackedTimestampSetSerialiserTest.java
Labels: tech-debt

#3263 Gh-3254: Standardise Spring REST user authentication
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IGraphConfigurationController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IJobController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IOperationController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IPropertiesController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IStatusController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/JobController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/OperationController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/PropertiesController.java
  rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/StatusController.java
  rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/OperationControllerTest.java
Labels: enhancement, rest-api
